name: graph_attribution
channels:
- rdkit
- conda-forge
dependencies:
- pip
- rdkit
- numpy
- ipython
- jupyter
- matplotlib
- numpy
- pandas
- scipy
- seaborn
- tqdm
- scikit-learn
- networkx
- pip:
        - tensorflow
        - git+https://github.com/deepmind/sonnet.git
        - graph_nets
        - typed-argument-parser
        - git+https://github.com/bp-kelley/descriptastorus
        - git+https://gitlab.com/Xiangyan93/graphdot.git@feature/xy
        - mgktools==0.0.4
